# Generated by Django 5.0.14 on 2025-09-06 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gourmet_app', '0002_stocktransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
