# Generated by Django 5.0.14 on 2025-09-08 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gourmet_app', '0004_alter_sale_amount_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='gourmet_app.party'),
        ),
    ]
